// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using capsproject.Data;

#nullable disable

namespace capsproject.Migrations
{
    [DbContext(typeof(DriveWiseContext))]
    partial class DriveWiseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("capsproject.Models.FloodPolygon", b =>
                {
                    b.Property<Guid>("PolygonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DangerLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrentlyFlooded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastStatusChange")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Polygon>("ZoneGeometry")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.HasKey("PolygonId");

                    b.HasIndex("NodeId");

                    b.ToTable("FloodPolygons");
                });

            modelBuilder.Entity("capsproject.Models.FloodTelemetry", b =>
                {
                    b.Property<long>("TelemetryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TelemetryId"));

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WaterDepthCM")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("TelemetryId");

                    b.HasIndex("NodeId");

                    b.ToTable("FloodTelemetries");
                });

            modelBuilder.Entity("capsproject.Models.SensorNode", b =>
                {
                    b.Property<Guid>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseElevationMeter")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Point>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NodeId");

                    b.ToTable("SensorNodes");
                });

            modelBuilder.Entity("capsproject.Models.FloodPolygon", b =>
                {
                    b.HasOne("capsproject.Models.SensorNode", "SensorNode")
                        .WithMany("FloodZones")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorNode");
                });

            modelBuilder.Entity("capsproject.Models.FloodTelemetry", b =>
                {
                    b.HasOne("capsproject.Models.SensorNode", "SensorNode")
                        .WithMany("TelemetryReadings")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SensorNode");
                });

            modelBuilder.Entity("capsproject.Models.SensorNode", b =>
                {
                    b.Navigation("FloodZones");

                    b.Navigation("TelemetryReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
